services:
  - type: web
    name: beautysphere
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Será configurado manualmente no dashboard do Render 